#!/bin/bash

if [ $# -eq 0 ]
  then
    echo "No arguments supplied"
    echo "Please input the g_code file you need converted: "
    read GCODE_FILE
  else
  	GCODE_FILE=$1
fi

echo "Cleaning $GCODE_FILE . . ."
echo "Expecting RepRap g_code flavour"

sed -i '' 's/G1/G01/g' $GCODE_FILE # Positional command syntax fix
sed -i '' 's/G92 E0/M05/g' $GCODE_FILE # Turning off spindle syntax
sed -i '' 's/E.*/M03/g' $GCODE_FILE # Turning on spindle syntax
sed -i '' 's/X-/X/g' $GCODE_FILE # Inverting X direction
sed -i '' 's/X/X-/g' $GCODE_FILE  
sed -i '' 's/Z-/Z/g' $GCODE_FILE # Inverting Z direction
sed -i '' 's/Z/Z-/g' $GCODE_FILE 

echo "Fixed the g_code to match syntax of Andrew's upcycled printer"
echo "Done."